### ISSUE TITLE
[request] Output formatters

### ISSUE THREAD

**Issue by tomholford** [ashelkovnykov/offline-wallet-generator#11]
It would be useful to support multiple output formats like JSON, YAML, etc. so that this tool can be used in a multi-step pipeline, or it's output consumed by other applications.

E.g.,

```sh
bin/owg-local.sh -o ~/.wallets/test.json -p cold -c BTC --format json
```

_test.json_
```json
{
  "createdAt": 1635296673,
  "currency": "BTC",
  "mnemonic": "test test test ... test",
  "xpub": "zpub123456.....lskdfjasdklfj",
  "accounts": [
    {
      "address": "0x12345...ABCD",
      "path": "m/44'/60'/0'/0/0"
    },
  ]
}
```

**Comment by ashelkovnykov** [comment]
This is a good idea. Will add a framework (but no additional formats, for now) in the near future.

**Comment by ashelkovnykov** [comment]
@tomholford 
Added a framework to add custom output types. If you want to add a JSON or YAML output type, you should be able to use the existing Java code for inspiration (you know JS - that should be close enough, right?).

If you're otherwise preoccupied and you really need JSON and/or YAML output, I can do it for you.

**Comment by ashelkovnykov** [comment]
Closing issue, since there is no longer a blocker for anyone to add any output format that they wish.
